name: Build and test

on:
  push:
    branches: [main]
    
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
    
jobs:
  build:
    runs-on: macos-15 # dotnet SDK 9.0.2 is implicitly installed on this
    steps:
      - uses: actions/checkout@v4
        
      - name: Use XCode 16.3
        run: sudo xcode-select -switch /Applications/Xcode_16.3.app
        
      - name: Install dotnet workload to compile for macOS
        run: dotnet workload install macos
        
      - name: Restore NuGet packages
        run: dotnet restore
        
      - name: Build application
        run: dotnet build --configuration Release --no-restore
